[global]
error_log = /proc/1/fd/2

[www]
listen = 127.0.0.1:9000
clear_env = no
catch_workers_output = yes
decorate_workers_output = no
access.log = /proc/1/fd/2
php_admin_value[error_log] = /proc/1/fd/2
php_admin_flag[log_errors] = on
